# Generated by Django 4.1.7 on 2023-02-27 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menu_menuitem_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='label',
            new_name='title',
        ),
    ]
